"""
Report Agent — generates Markdown and PDF pipeline reports.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

import pandas as pd

from services.storage_service import StorageService
from utils.logger              import get_logger

logger = get_logger(__name__)

_MD_PATH  = "reports/report.md"
_PDF_PATH = "reports/report.pdf"


class ReportAgent:
    """Produces a Markdown report and a PDF report from pipeline artefacts."""

    def __init__(self, storage: StorageService) -> None:
        self._storage = storage

    # ── Public ────────────────────────────────────────────────────────────────

    def generate_markdown(
        self,
        description:     str,
        df_raw:          pd.DataFrame,
        df_clean:        pd.DataFrame,
        kpis:            dict,
        spark_metrics:   dict,
        insights:        str,
        cleaning_report: dict,
    ) -> str:
        """
        Build and save a comprehensive Markdown report.

        Returns:
            Relative path of the saved report.
        """
        ts     = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        engine = spark_metrics.get("engine", "pandas").upper()

        md = f"""# 📊 Agentic Data Engineering Pipeline Report

**Generated:** {ts}
**Dataset Description:** {description[:300]}
**Processing Engine:** {engine}

---

## 1. Executive Summary

This report summarises the end-to-end agentic data engineering pipeline run.
The pipeline ingested a synthetic dataset, cleaned it, applied feature
engineering and transformations, performed distributed analytics, and generated
the KPIs and insights below.

---

## 2. Dataset Statistics

| Metric | Raw | Cleaned |
|---|---|---|
| Rows | {len(df_raw):,} | {len(df_clean):,} |
| Columns | {len(df_raw.columns)} | {len(df_clean.columns)} |
| Duplicates Removed | — | {cleaning_report.get('duplicates_removed', 0)} |
| Missing Values Filled | — | {len(cleaning_report.get('missing_filled', {}))} |

### Raw Column Names
`{', '.join(df_raw.columns.tolist())}`

---

## 3. KPI Dashboard

| KPI | Value |
|---|---|
{self._kpi_table_rows(kpis)}

---

## 4. {engine} Analysis

**Engine:** {engine}
**Rows Processed:** {spark_metrics.get('row_count', 0):,}
**Columns Processed:** {spark_metrics.get('col_count', 0)}

### Numeric Summary
{self._numeric_summary_md(spark_metrics.get('numeric_summary', {}))}

### Top Categories
{self._top_categories_md(spark_metrics.get('top_categories', {}))}

---

## 5. AI-Generated Business Insights

{insights}

---

## 6. Pipeline Steps Completed

1. ✅ DatasetAgent — synthetic data generation
2. ✅ CleaningAgent — deduplication & imputation
3. ✅ TransformationAgent — feature engineering, encoding, scaling
4. ✅ SparkAgent — distributed aggregations ({engine})
5. ✅ AnalyticsAgent — KPI computation & LLM insights
6. ✅ ReportAgent — Markdown & PDF generation

---

*Report generated by Agentic Data Engineering Pipeline*
"""
        path = self._storage.save_text(md, _MD_PATH)
        logger.info("Markdown report saved | path=%s", path)
        return _MD_PATH

    def generate_pdf(
        self,
        description:   str,
        kpis:          dict,
        spark_metrics: dict,
        insights:      str,
    ) -> str:
        """
        Build and save a PDF report using ReportLab.

        Returns:
            Relative path of the saved PDF.
        """
        try:
            return self._build_pdf(description, kpis, spark_metrics, insights)
        except ImportError:
            logger.warning("reportlab not installed — skipping PDF generation.")
            return ""
        except Exception as exc:
            logger.error("PDF generation failed: %s", exc)
            return ""

    # ── PDF builder ───────────────────────────────────────────────────────────

    def _build_pdf(
        self,
        description:   str,
        kpis:          dict,
        spark_metrics: dict,
        insights:      str,
    ) -> str:
        from reportlab.lib                import colors
        from reportlab.lib.pagesizes     import A4
        from reportlab.lib.styles        import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units         import cm
        from reportlab.platypus          import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
        )

        abs_path = os.path.abspath(
            os.path.join(os.path.dirname(__file__), "..", _PDF_PATH)
        )
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)

        doc    = SimpleDocTemplate(abs_path, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm,
                                   topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()
        story  = []

        # ── Title ──────────────────────────────────────────────────────────────
        title_style = ParagraphStyle("Title2", parent=styles["Title"], fontSize=18, spaceAfter=6)
        story.append(Paragraph("Agentic Data Engineering Pipeline Report", title_style))
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        story.append(Paragraph(f"Generated: {ts}", styles["Normal"]))
        story.append(Spacer(1, 0.3*cm))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
        story.append(Spacer(1, 0.3*cm))

        # ── Description ────────────────────────────────────────────────────────
        story.append(Paragraph("Dataset Description", styles["Heading2"]))
        story.append(Paragraph(description[:400], styles["Normal"]))
        story.append(Spacer(1, 0.4*cm))

        # ── KPI table ──────────────────────────────────────────────────────────
        story.append(Paragraph("KPI Dashboard", styles["Heading2"]))
        kpi_rows  = [["KPI", "Value"]]
        skip_keys = {"cleaning_summary", "dist_", "top_"}
        for k, v in kpis.items():
            if any(k.startswith(s) for s in skip_keys):
                continue
            if isinstance(v, (dict, list)):
                continue
            kpi_rows.append([str(k).replace("_", " ").title(), str(v)])

        kpi_table = Table(kpi_rows, colWidths=[9*cm, 7*cm])
        kpi_table.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), colors.HexColor("#4472C4")),
            ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#EBF1F9")]),
            ("GRID",        (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("PADDING",     (0, 0), (-1, -1), 5),
        ]))
        story.append(kpi_table)
        story.append(Spacer(1, 0.5*cm))

        # ── Spark/Pandas metrics ───────────────────────────────────────────────
        engine = spark_metrics.get("engine", "pandas").upper()
        story.append(Paragraph(f"{engine} Analysis", styles["Heading2"]))
        story.append(Paragraph(
            f"Rows: {spark_metrics.get('row_count', 0):,} | "
            f"Columns: {spark_metrics.get('col_count', 0)}",
            styles["Normal"],
        ))
        story.append(Spacer(1, 0.4*cm))

        # ── Insights ───────────────────────────────────────────────────────────
        story.append(Paragraph("AI-Generated Business Insights", styles["Heading2"]))
        clean_insights = insights.replace("**", "").replace("##", "").replace("#", "")
        for line in clean_insights.splitlines():
            line = line.strip()
            if line:
                story.append(Paragraph(line, styles["Normal"]))
                story.append(Spacer(1, 0.1*cm))
        story.append(Spacer(1, 0.4*cm))

        # ── Footer ─────────────────────────────────────────────────────────────
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
        story.append(Paragraph("Generated by Agentic Data Engineering Pipeline", styles["Normal"]))

        doc.build(story)
        logger.info("PDF report saved | path=%s", abs_path)
        return _PDF_PATH

    # ── Markdown helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _kpi_table_rows(kpis: dict) -> str:
        rows = []
        skip = {"cleaning_summary"}
        for k, v in kpis.items():
            if k in skip or isinstance(v, (dict, list)):
                continue
            label = k.replace("_", " ").title()
            rows.append(f"| {label} | {v} |")
        return "\n".join(rows) if rows else "| — | — |"

    @staticmethod
    def _numeric_summary_md(summary: dict) -> str:
        if not summary:
            return "_No numeric summary available._"
        rows = ["| Column | Mean | Std | Min | Max |", "|---|---|---|---|---|"]
        for col, stats in summary.items():
            rows.append(
                f"| {col} | {stats.get('mean','—')} | {stats.get('std','—')} "
                f"| {stats.get('min','—')} | {stats.get('max','—')} |"
            )
        return "\n".join(rows)

    @staticmethod
    def _top_categories_md(top_cats: dict) -> str:
        if not top_cats:
            return "_No categorical data available._"
        sections = []
        for col, counts in top_cats.items():
            rows = [f"**{col}**", "| Value | Count |", "|---|---|"]
            for val, cnt in counts.items():
                rows.append(f"| {val} | {cnt} |")
            sections.append("\n".join(rows))
        return "\n\n".join(sections)
